uktrade/data-flow

dataflow/dags/view_pipelines.py
dataflow/operators/dataset.py

Add 2 new monthly view pipelines for data hub outputs:
1. Service deliveries and interactions
2. Export client survey

Add data hub interaction views

---

dataflow/dags/view_pipelines.py

Adds a new monthly materialized view based on the daily FDI data cut

Add monthly static FDI report

---

dataflow/dags/view_pipelines.py

Ensure OMIS all orders report runs on the first of the month for the full previous month

Fix date format and date range of omis all orders report

---

dataflow/dags/view_pipelines.py

Display all related team names/roles in a single field in investment project views

Display all investment project team roles and names

---

.gitignore
CHANGELOG.md
dataflow/config.py
dataflow/dags/company_matching.py
dataflow/operators/activity_stream.py
dataflow/operators/api.py
dataflow/operators/company_matching.py
sample.env
tests/operators/test_activity_stream.py

company matching pipeline

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py
dataflow/operators/db_tables.py
tests/operators/test_db_tables.py

Allow for turning off null column validation at the pipeline level.

Add ability to disable null column checks per pipeline.

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py

Add the missing static flag to the fdi report

Ensure fdi report is not updated

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

Add `created_by_id` to interactions dataset to match response from data hub.

Add `created_by_id` to interactions dataset.

---

dataflow/dags/dataset_pipelines.py

Add new dag for the export_country_history_dataset

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/market_access_pipelines.py
dataflow/dags/spi_pipeline.py
dataflow/transforms.py
dataflow/utils.py
requirements.in
sample.env

Pipeline implementation for market access trade barriers from their v1
API. Spec here: https://github.com/uktrade/market-access-api/blob/v1/api/dataset/serializers.py
Ticket: https://trello.com/c/cMZD5r7q/837

Market access trade barriers pipeline

---

README.md

Add details for setting up local dev env

---

CHANGELOG.md
dataflow/dags/company_matching.py
dataflow/dags/dataset_pipelines.py

Migrate more pipelines to using `TableConfig`.

Migrate more pipelines to TableConfig

---

dataflow/dags/dataset_pipelines.py

Migrate missed pipeline

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/consent_pipelines.py
dataflow/operators/common.py
sample.env
tests/test_dags.py

Add Consent API DAG

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

This adds pipelines to add the world bank data as we receive it before transformation.

Raw world bank tariff pipelines

---

dataflow/dags/activity_stream_pipelines.py
dataflow/dags/base.py
dataflow/dags/company_matching.py
dataflow/dags/dataset_pipelines.py
dataflow/dags/fdi_dashboard.py
dataflow/dags/hmrc_pipelines.py
dataflow/dags/ons_pipelines.py

Migrate all pipelines to use TableConfig

---

dataflow/dags/market_access_pipelines.py

`barrier_types` was renamed to `categories` in source API

---

dataflow/utils.py

Add links to logs for failed tasks

---

dataflow/dags/maintenance.py

Add Slack alerts for maintenance DAG

---

.gitignore
CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_pipelines.py
tests/test_dags.py

Dataset 3 and 4 - https://drive.google.com/file/d/1XntCt2sMgPxgKnr_vT2eZmtQ_REBwkXf/view?ths=true

Add CSV pipelines for UK trade/total trade in services

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py

Do not include rejected wins in the daily export wins report

Ensure rejected wins are not included in daily wins report

---

dataflow/dags/dataset_pipelines.py
tests/test_dags.py

remove deprecated datasets (company_export_to_countries and company_future_interest_countries)

---

tests/test_dags.py

Update number of pipelines for tests

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

Increase interactions dataset page_size to 10k

---

CHANGELOG.md
dataflow/dags/consent_pipelines.py

Allow duplicate ids in consent dataset

Do not set a primary on consent id

---

dataflow/dags/dashboard_pipelines.py

Fix issue where postgres date is not json serializable

Force date to text data type for consumption on data flow

---

dataflow/dags/dashboard_pipelines.py

Fix incorrect data type on dashboard column

---

dataflow/dags/export_wins_dashboard.py
tests/test_dags.py

add new export_wins_dashboard dag

---

dataflow/dags/dashboard_pipelines.py
tests/test_dags.py

- Fix test caused by pervious merge
- Fix incorrect column name

Fix tests and fix column name error

---

CHANGELOG.md
dataflow/utils.py
requirements-dev.txt
tests/test_utils.py

Support json serialization for date/datetime

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

- Add requested primary key to ministerial interactions dataset
- Fix lat/lng spacing on the same
- Remove date -> text data type conversion

Update ministerial interactions to include a primary key

---

dataflow/dags/dashboard_pipelines.py

In the last of this series... Replace uuid primary key with text.

Set primary ket to text rather than uuid

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

Adds an auto incrementing int as primary key

Replace text primary key with auto incrementing integer

---

dataflow/dags/export_wins_dashboard.py

add primary key to export wins dashboard

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

- Fixes the issue where google data studio was unable to read column names

Join column names with underscores on ministerial interactions dataset

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/dun_and_bradstreet_pipelines.py
dataflow/operators/common.py
sample.env
tests/operators/test_dataset.py
tests/test_dags.py

Adds a pipeline for dun and bradstreet companies sourced from the dnb-service.

Add dnb pipeline

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

Fix typo in column name

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

Stop casting everything to `::text` for the fdi dashboard

Remove unnecessary text casting

---

CHANGELOG.md
dataflow/utils.py
tests/test_utils.py

Allow for writing decimals to s3

JSON encode decimals

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_parsing_pipelines.py
dataflow/ons_scripts/uktotaltradeallcountriesnonseasonallyadjusted/__init__.py
dataflow/ons_scripts/uktotaltradeallcountriesnonseasonallyadjusted/info.json
dataflow/ons_scripts/uktotaltradeallcountriesnonseasonallyadjusted/main.py
dataflow/ons_scripts/uktradeinservicesservicetypebypartnercountrynonseasonallyadjusted/__init__.py
tests/test_dags.py

ONS Dataset 4.
Ticket: https://trello.com/c/TZQ1COLF/1115

ONSUKTotalTradeAllCountriesNSA

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py

Add trade balance/total trade to dataset 4 csv export

---

CHANGELOG.md
Procfile
dataflow/dags/ons_parsing_pipelines.py
dataflow/ons_scripts/uktradecountrybycommodity/__init__.py
dataflow/ons_scripts/uktradecountrybycommodity/exports.py
dataflow/ons_scripts/uktradecountrybycommodity/imports.py
dataflow/ons_scripts/uktradecountrybycommodity/info.json
dataflow/ons_scripts/uktradecountrybycommodity/main.py
dataflow/operators/db_tables.py
dataflow/operators/ons.py
docker-compose.yml
tests/test_dags.py

Add initial pipeline for ONS dataset 2 - not yet handling the CSV export.
This pipeline will run its ingest task via a separate worker specifically for 'heavy' (in terms of memory) tasks. We'll set this up initially with 4-5G RAM, which should be sufficient.
Ticket: https://trello.com/c/Y0rkEQaI/1118

Ons dataset 2

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_yearly.py
tests/test_dags.py

Adds export wins by financial year dag

New yearly csv pipeline for export wins by financial year

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_parsing_pipelines.py

And change schedule to match ONS release schedule.

Add product name to ONS datset 2 csv export

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

Data Hub PR: https://github.com/uktrade/data-hub-api/pull/2932

Add column to Interactions Dataset

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/sharepoint_pipelines.py
dataflow/operators/sharepoint.py
requirements.in
requirements.txt
sample.env
tests/operators/test_sharepoint.py
tests/test_dags.py

- Adds a new sharepoint fetch operator using [msal](https://github.com/AzureAD/microsoft-authentication-library-for-python) for authentication
- Adds 2 new information asset datasets
This pipeline has been tested on the azure reference tenant but will be disabled initially while production authentication is sorted out with the supplier.

IAR sharepoint pipelines

---

CHANGELOG.md
dataflow/operators/db_tables.py
tests/operators/test_db_tables.py

Use schema when granting permissions to tables

Ensure correct schema is used when granting permissions to swapped table

---

dataflow/dags/covid19_pipelines.py

Run CSSE COVID pipeline after the daily data update at 5am

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_parsing_pipelines.py

This is a draft PR pending James and Owen's agreement/feedback.

Apply data standards to ONS dataset 3

---

CHANGELOG.md
dataflow/dags/ons_parsing_pipelines.py

Double underscoring to meet data standards on ONS dataset 3

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

Adds some new fields to data hub datasets.

Add additional fields to data hub datasets

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_parsing_pipelines.py
dataflow/ons_scripts/uktradecountrybycommodity/exports.py
dataflow/ons_scripts/uktradecountrybycommodity/imports.py

Update ONS datasets 2 and 4 to more closely align with our data standards doc: https://docs.google.com/document/d/16CR9drESzON86rx89pOrKl1gKXnxBnPjAhbIZilFzrk/edit#heading=h.qf0sshj8a08g

Ons 2 4 standards

---

CHANGELOG.md
dataflow/dags/ons_parsing_pipelines.py

Move from daily to monthly schedule

---

dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_pipelines.py

Marker is set to not-applicable to JE region records, which
don't have a value in the original dataset.
Updates column names to match other ONS datasets.

Add marker field to ONS dataset 1 and update column names

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

Update fdi dashboard query to include investment projects with an estimated OR actual land date in the current financial year.
* Query provided by Anthony Love

Update filters for FDI dashboard DAG

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py
tests/test_dags.py

There will likely be more fields added in later versions, but for a v1.

Staff SSO users pipeline

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py

~* [ ] Have tests been added to cover any changes?~
~* [ ] Has the README been updated (if needed)?~

Add last access time to sso

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py
dataflow/utils.py
tests/unit/test_utils.py

Include permitted applications for each user in SSO

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py

Requested by Anthony
~* [ ] Have tests been added to cover any changes?~
~* [ ] Has the README been updated (if needed)?~

Add joined date to Staff SSO users

---

CHANGELOG.md
dataflow/dags/market_access_pipelines.py

Add `commercial_value_explanation` to MarketAccessBarriersPipeline

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py
dataflow/dags/dataset_pipelines.py

Revert "Remove contacts email marketing field"

---

dataflow/dags/base.py

The old structure incorrectly had both 'swap-dataset-tables' and
'check-temp-table-data' following on from 'transform tables' task,
rather than transform leading to check leading to swap.

Restructure task flow

---

dataflow/operators/contact_consent.py

Email is turned to lower case in Consent Service during save. But Data Hub doesn't. So we need to lower and join in our matching code.

join lowered email between contacts and consent

---

CHANGELOG.md
dataflow/dags/covid19_pipelines.py

Adds some extra transformations as requested by data scientists.

Add some more transformations for google mobility data

---

dataflow/dags/market_access_pipelines.py

fix: remove `unarchived_by` field

---

CHANGELOG.md
dataflow/dags/dun_and_bradstreet_pipelines.py
dataflow/operators/dun_and_bradstreet.py
tests/unit/operators/test_dun_and_bradstreet.py
tests/unit/test_dags.py

- Fetches company updates since the last DAG run from the DNB service
- Imports data into temporary tables
- Update global company and reference number tables from the temp tables
- drop temp tables
Closes: https://trello.com/c/0wo4a6X3/641-dnb-company-update-pipeline

feat: dnb company pipeline to sync changes from the dnb service

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py

fix: rename great gov forms pipeline

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

feat: add sso email to advisers dataset

---

CHANGELOG.md
dataflow/operators/dss_generic.py

fix: support numeric data type in generic dss pipeline

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py
tests/unit/test_dags.py

- Query provided by Anthony Love
- Required for recreating alteryx reports for the Investment Promotion Performance team
- Will be used as the base table to create up ~100 monthly sql reports to be published in the near future.

feat: monthly investment projects base table

---

CHANGELOG.md
dataflow/dags/company_matching.py
dataflow/dags/dss_generic_pipelines.py
dataflow/operators/dss_generic.py
tests/unit/test_dags.py

The dataset will be uploaded by the CSV uploader and then processed by the DSSGenericPipeline. 
At the end of the processing the matching pipeline is triggered to get match_ids for the data.

feature: hmrc field_force matching pipeline

---

dataflow/dags/company_matching.py

Updated table name for hmrc field force matching

update field force table name

---

dataflow/dags/company_matching.py

Shorter matching table name to avoid exceeding max column length on swap

update field force matching table name

---

.env.test
CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/ons_pipelines.py
dataflow/operators/db_tables.py
dataflow/operators/email.py
docker-compose.yml
requirements.in
requirements.txt
sample.env
tests/unit/dags/test_base.py
tests/unit/dags/test_ons_parsing_pipelines.py
tests/unit/dags/test_ons_pipelines.py
tests/unit/operators/test_email.py
tests/unit/utils.py

We are starting to onboard some datasets that users want to start
working with as soon as possible after the source data has been updated.
In aid of this we need a mechanism to notify users when data has been
updated so that they don't need to keep checking themselves.
We will use GOV.UK Notify to send templated emails when a pipeline
succeeds which contain a link to the relevant Data Workspace dataset
page as the MVP.

feat: send emails when a pipeline succeeds

---

.pre-commit-config.yaml

feat: add pre-commit config to match data workspace

---

dataflow/dags/dataset_pipelines.py

fix table names to be compatible with other tables

fix last transaction table name

---

CHANGELOG.md
dataflow/dags/derived_report_table_pipelines.py

fix: export wins derived dag typo

fix: export wins derived dag typo

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py

fix: return to office user id should be an integer

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py

Use the `bookingId` field rather than the activity stream id

fix: Use the correct booking id field

---

dataflow/dags/activity_stream_pipelines.py
dataflow/dags/company_matching.py

Test case for rename tables according to data workspace standards. When merging this PR the old
table will (manually) be replaced by a view pointing to this new table until all dependencies in DW (datacuts, visualisations, etc.) are migrated to use the new table and users had a chance to make any required code changes in tools.

Table renaming: export opportunities

---

CHANGELOG.md
docker-compose.yml
requirements.in
requirements.txt

Add [prometheus metrics exporter](https://github.com/uktrade/data-flow-metrics) to data-flow.

Data flow metrics

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

Ingests are still being flakey: being killed for no known reason (although speculating they are running out of memory).

feat: retry all _DatasetPipeline 3 times

---

CHANGELOG.md
dataflow/dags/market_access_pipelines.py

5 new fields added to market access pipeline
- trading_bloc_code
- trading_bloc_name
- end_date
- summary
- wto_profile
Closes: https://trello.com/c/lVIzGQZ7/1020-add-fields-to-market-access-pipeline

feat: add 5 fields to the market access pipeline

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

Adds export revenue to the fdi dashboard pipeline to save extra joins when querying

feat: new field export_revenue added to fdi pipeline

---

CHANGELOG.md
dataflow/dags/cabinet_office_pipelines.py
dataflow/operators/cabinet_office.py
tests/unit/operators/test_cabinet_office.py
tests/unit/test_dags.py

New pipeline for gender pay gap data backed by csvs hosted by cabinet office.
Closes: https://trello.com/c/tbB2hDlA/137-gender-pay-gap

feat: add new gender pay gap pipeline

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

Update the final query using the old postcodes table to use the new materialized view

fix: use materialized view for postcodes

---

dataflow/operators/tags_classifier_model/setting.py

threshold change

---

dataflow/dags/activity_stream_pipelines.py
tests/unit/test_dags.py

New activity stream pipeline for great.gov.uk companies
Depends on: https://github.com/uktrade/directory-api/pull/774
Closes: https://trello.com/c/1TpkXaAI/52-greatgovuk-company-profiles

feat: add great.gov.uk companies pipeline

---

dataflow/operators/contact_consent.py

fix: add missing dot

---

dataflow/dags/activity_stream_pipelines.py
tests/unit/test_dags.py

feat: separate table for MaxEmail campaigns, and store more MaxEmail events

---

dataflow/dags/data_workspace_pipelines.py

The `extra` field includes arbitrary JSON for each event, which often
includes important/useful data. For example, for saved Data Explorer
queries, it includes the SQL that was saved.

feat: add extra to eventlog pipeline

---

dataflow/dags/activity_stream_pipelines.py

feat: more appropriate started type for MaxEmail campaigns

---

dataflow/dags/activity_stream_pipelines.py

feat: add status to Staff SSO dataset

---

dataflow/config.py
dataflow/dags/hmrc_pipelines.py
dataflow/operators/hmrc.py
requirements-tensorflow.txt
requirements.in
requirements.txt
tests/unit/operators/test_hmrc.py

fix: HMRC pipelines to work with their new website structure

---

dataflow/operators/tags_classifier_model/setting.py

merge tags

---

dataflow/dags/tags_classifier_pipeline.py

fix: tags classifier pipeline for updated schema/table

---

dataflow/dags/sharepoint_pipelines.py

fix: for InformationAssetRegisterPipeline changing how boolean values are exported

---

dataflow/dags/dashboard_pipelines.py

The new query was supplied by Teemerte in relation to the FDI investment projects datacut
https://trello.com/c/ePcmgXfG/283-update-materialised-view-for-the-monthly-fdi-investment-project-data-cut

feature: update query used in DataHubMonthlyInvesmentProjects pipeline

---

dataflow/dags/data_workspace_pipelines.py
tests/unit/test_dags.py

feature: add pipeline for data workspace catalogue items api

---

dataflow/dags/dashboard_pipelines.py

This field is no longer in the query

fix: remove fdi_value from DataHubMonthlyInvesmentProjects table conf

---

dataflow/dags/market_access_pipelines.py

feature: update MarketAccessTradeBarriersPipeline after API change

---

dataflow/dags/market_access_pipelines.py

fix: remove assessment_rating column as its no longer in the api

---

dataflow/dags/dashboard_pipelines.py

Aligning table config with query changes that were made earlier to Data Hub investment projects monthly pipeline.

align datahub investment monthly table config with sql query changes

---

dataflow/dags/market_access_pipelines.py

Market access pipeline table config need few changes as API response has changed significantly.
Here is the concerning part of the new API response:
```    "economic_assessments": [
{
"id": 1,
"approved": true,
"archived": false,
"archived_by": null,
"archived_on": null,
"archived_reason": "",
"automated_analysis_data": null,
"barrier_id": "123",
"created_by": {
"id": 223,
"name": "Foo bar"
},
"created_on": "2019-08-29T08:47:08.487872Z",
"documents": [
{
"id": "123",
"name": "B-19-ABC (services tax) summary.xlsx",
"size": 72903,
"status": "virus_scanned"
}
],
"economic_impact_assessments": [],
"explanation": "blah",
"export_value": 100,
"import_market_size": 100,
"modified_on": "2020-11-30T11:47:47.981305Z",
"modified_by": {
"id": 223,
"name": "Foo bar"
},
"rating": {
"code": "HIGH", …
```

realigning table config for market access

---

dataflow/dags/dashboard_pipelines.py

This PR is to make tiny sql changes, as requested, to Data Hub investment pipelines.

datahub investment pipeline sql change

---

dataflow/dags/market_access_pipelines.py

commenting out impact_assessments bit, in order to get market access pipeline running, while we figure out it structure.

removing impact_assessements for now, until we figure it out

---

dataflow/dags/dataset_pipelines.py

This PR is to migrate export wins advisers table to match the new standards

Migrate export wins advisers table to match data standards 

---

dataflow/dags/dataset_pipelines.py

Add new field project won date that was added to the investment dataset.

adding project_won field to investments dataset

---

dataflow/dags/company_matching.py
tests/unit/test_dags.py

Added DNB uk companies to company matching pipeline.
Not sure how to multiple names and addresses eg trading names, primary names etc

update company matching for dnb uk companies

---

dataflow/dags/export_wins_dashboard.py

fix: match IDs table name for export wins

---

dataflow/dags/covid19_pipelines.py

Fix accidental setting of results key to none during refactor :-(

fix: add result key back to covid pipelines

---

dataflow/dags/covid19_pipelines.py

Caught out by the swap table being > 63 chars issue

fix: shorten covid local authority table name

---

tests/unit/test_dags.py
tests/unit/utils.py

Test that table names are less than 42 chars long and schema names less than 63

feat: add test for table and schema name lengths

---

dataflow/dags/data_workspace_pipelines.py

Part of the full text search firebreak task.
Dependent on https://github.com/uktrade/data-workspace/pull/1162

feat: add source table and slug to dataset

---

dataflow/dags/market_access_pipelines.py

Adds new fields and nested tables to match the latest release of the market barriers api

feat: update pipeline to match new api release

---

tests/unit/test_dags.py
tests/unit/utils.py

We generally want to be moving away from the public schema for new
datasets, so let's add this test as a bit of a sense-check to catch
simple mistakes.

test: prevent new tables in public schema

---

tests/unit/test_dags.py

test/fix: wrong market access table names

---

dataflow/dags/hmrc_pipelines.py
dataflow/operators/hmrc.py
dataflow/utils.py
tests/unit/operators/test_hmrc.py
tests/unit/test_dags.py

There is a bit of apparent duplication in some of the `utils.py` code, but leaving that as is

feat: HMRC EU export estimates

---

dataflow/dags/hmrc_pipelines.py
tests/unit/test_dags.py

feat: HMRC EU import estimates

---

dataflow/dags/hmrc_pipelines.py
dataflow/operators/hmrc.py
tests/unit/operators/test_hmrc.py
tests/unit/test_dags.py

Some of the data is not UTF-8. Not sure if it's corrupted, or some other encoding. Opting to replace any characters that can't be parsed.

feat: HMRC control pipeline

---

dataflow/dags/company_matching.py

This is to fix broken DNB company matching pipeline for Data Science team.

fixing DNB company matching pipeline
