uktrade/data-flow

dataflow/meta/dataset_pipelines.py

Following the new data-hub advisers dataset endpoint added in
uktrade/data-hub-leeloo#2187, this adds the import pipeline to
create advisers table and load the data from data-hub.

Add Advisers dataset pipeline

---

dataflow/meta/dataset_pipelines.py

Used to import teams data from datahub. One thing to note is that
currently datahub endpoint is only ordered by ID (which is a UUID),
so it's possible that pagination will break (by including an item
more than once) if a new team is created during the import. Teams
don't have a creation date column, so there's no other way to order
them at the moment, but the table shouldn't change too often.

Add teams dataset pipeline

---

.circleci/config.yml
Makefile
dataflow/airflow_login.py
dataflow/dags/dataset_pipelines.py
dataflow/dags/view_pipelines.py
dataflow/meta/dataset_pipelines.py
dataflow/meta/view_pipelines.py
dataflow/utils.py
dataflow_worker_dummy_app.py
requirements-dev.txt
setup.cfg

Used to import teams data from datahub. One thing to note is that currently datahub endpoint is only ordered by ID (which is a UUID), so it's possible that pagination will break (by including an item more than once) if a new team is created during the import. Teams don't have a creation date column, so there's no other way to order them at the moment, but the table shouldn't change too often.
Adds a separate requirements file that can be used in CI or dev docker images to run static analysis tools and tests in the future.
Installs flake8 for code style checks, black for autoformatting and mypy for type hints validation.
Some of the libraries we're using don't have type hints, so we can disable missing import errors for the time being.
This is the result of running `make format` for the …

Add static code analysis checks

---

dataflow/operators/dataset.py

This fixes the issue where an empty response from datahub was causing the insert task to fail as there was no data in the insert statement.

Fix empty response task failure

---

dataflow/operators/dataset.py

Calling `decode()` on the var name returned from redis was causing `AttributeError: 'str' object has no attribute 'decode'`

Remove unnecessary decode on string returned from redis

---

dataflow/dags/activity_stream_pipelines.py
dataflow/operators/activity_stream.py
tests/operators/test_activity_stream.py

This updates activity stream operators to use /v3/ API and paginate
based on `search_after` instead of `from`. Search after doesn't have
offset restrictions, so can be used to download large datasets.
This also moves size/sort parts of the query to the fetch operator
itself, so the DAG query should only contain the `"query"` part
itself (for example filters).

Use /v3/ activity-stream API and search_after pagination

---

Jenkinsfile

Promotion pipeline should consistently move the same commit through
dev, staging and prod, even if there were new merges into master
since the job has initially been started.
The easiest way to set a variable that is available in all stages of
the Jenkins Pipeline and doesn't require an agent to access seems to
be to set a parameter when starting the build. This changes the job
to accept GIT_COMMIT parameter, checkout that specific commit to
populate build name with a PR number and then call ci-pipeline with
it.
In order to set the commit parameter automatically on each master merge
this job will be started by another Jenkins job, which watches the Github
repo.

Release a specific commit through all CI stages

---

dataflow/dags/activity_stream_pipelines.py
dataflow/operators/activity_stream.py
dataflow/operators/db_tables.py
requirements.in
requirements.txt
setup.cfg
tests/operators/test_activity_stream.py
tests/operators/test_db_tables.py

ERP form has 4 possible user flows, which result in slightly different object schemas. This adds fields from all 4 possible responses and a `url` field that contains the type of the response into the ERP dataset table.
provide_context no longer seems to pass user_defined_macros as args in Airflow 1.10.6, so we provide `run_fetch_task_id` explicitly to tasks that rely on it
Adds 2 simple checks to verify dataset import is operating as intended:
1. Compares the sizes of the new import and existing dataset and aborts the table swap if the new dataset is more than 10% smaller than the existing one. This only runs if the dataset already exists.
2. Checks if any columns only have NULL values (and are therefore either unused or being imported from a wrong field, for example due to a typo).
For …

Add a full list of ERP fields for 4 user flows

---

Jenkinsfile

Locks ci-pipeline job for each environment so that consecutive
merges wait until the previous release to the given environment
has completed.
ci-pipeline would prevent a concurrent run for the same project,
the difference is this delays the job run instead of failing it.

Prevent concurrent releases to the same environment

---

dataflow/dags/activity_stream_pipelines.py
dataflow/utils.py

Adds pipelines to import great.gov.uk export opportunities and
export opportunity enquiries datasets from the activity stream API.
Two datasets are connected by id - `enquiries.opportunity_id` should
match with `opportunity.id`.
Enquiries contain company and person data as 2 items in the `actor`
array, so for the time being we're extracting them by indexing into
the array (first record is the company, second is the person). This
works because the order seems to always be the same, but will raise
an error if the records are switched since `name` types are different.
This can be generalised by extending `get_nested_key` to match based
on a predicate instead of fixed index in the future.

Add great.gov.uk export opportunities and enquiries

---

requirements.in
requirements.txt

We've had daily jobs failures with tasks failing to be scheduled
that started happening after the Airflow upgrade, so we're rolling
it back for the time being to investigate if it's related to any
of the 1.10.6 changes.
This will rollback the Sentry integration but shouldn't affect
anything else.

Rollback airflow to investigate daily job failures

---

dataflow/dags/activity_stream_pipelines.py

Some fields weren't previously being published by the ERP service.
This adds the missing fields to the ERP pipeline.

Add additional fields for the revised ERP schemas

---

dataflow/config.py
dataflow/dags/ons_pipelines.py
dataflow/operators/ons.py
tests/operators/test_ons.py

gss-alpha wraps another ONS SPARQL endpoint that we can use directly.
Since it doesn't support pagination arguments we need to modify the query with LIMIT and OFFSET parameters.
This implements the "cursoring" approach proposed by ONS: we split the dataset into smaller ones by first getting a list of all possible values for one or more dimensions (e.g. geography or year/month) and then requesting data for each value (or combination of values) of these dimensions.
In order to achieve this we add an optional `index_query` to the ONS pipeline class. This query returns a list of values used to parameterize the dataset query in order to filter out results. The query should also return a `label` value, which is used to prefix page response file names stored in S3.
Index query is currently not …

Split ONS UK trade data dataset import by the time period

---

CHANGELOG.md
dataflow/dags/ons_pipelines.py

The two datasets added here are:
* UK trade in services: total by flow and country, non-seasonally adjusted
* UK trade in services: total by service type, flow and country,
non-seasonally adjusted.
Ticket: https://trello.com/c/T4qi6vPG/836
These datasets are intended to be comparable to [UK trade in services: service type by partner country, non-seasonally adjusted](https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/datasets/uktradeinservicesservicetypebypartnercountrynonseasonallyadjusted) and [UK trade in services: all countries, non-seasonally adjusted](https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/datasets/uktradeinservicesallcountriesnonseasonallyadjusted), however GSS data doesn't seem to have datasets that match these names exactly.
One of them …

Add pipelines for two more ONS datasets

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/dataset_pipelines.py
sample.env

This adds ONS Postcode pipeline that retrieves its data from the data-store-service
`DATA_STORE_SERVICE_BASE_URL` has been added to vault on all platforms

ONS Postcodes from data-store-service added

---

docker-compose.yml

On running `docker-compose up`, I got the following error from the Postgres image:
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD for the superuser. Use
"-e POSTGRES_PASSWORD=password" to set it in "docker run".
You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
without a password. This is *not* recommended. See PostgreSQL
documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
```
This error stops the Postgres container from launching, causing data-flow to error out
trying to connect to the db.
Although it says it isn't recommended, I think allowing no password in docker-compose is probably ok.
Test is that `docker-compose up` works. I think this change is not notable …

Stop Postgres wanting a password in docker-compose

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py

This was removed accidentally in the switch to csv outputs
Add ordering back to cancelled omis orders report.

Add ordering to cancelled omis order report.

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py

- Ensure all fdi records, up to the current time, are included in the daily report.
- Indent the daily fdi query properly to ease readibility 
Unfortunately fixing the indents on the query makes it hard to spot the change. The main change is to switch from using `:run_date` to `now()` to filter records.

Include all fdi investments up to current date in daily report

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py
dataflow/dags/csv_pipelines/csv_pipelines_yearly.py

- Join string arrays using semi colons on fdi report
- Do not include business activities that are an empty string in fdi report
- Ensure omis orders are included to the end of the month for the given run date
- Set null and false values to false in export wins early cut

CSV report query cleanup

---

CHANGELOG.md
dataflow/logging_config.py
dataflow/operators/activity_stream.py
dataflow/operators/api.py
dataflow/operators/company_matching.py
dataflow/operators/csv_outputs.py
dataflow/operators/dataset.py
dataflow/operators/db_tables.py
dataflow/operators/ons.py
dataflow/utils.py

Airflow upgrade changed something in the logging configuration so
our operator log messages were no longer included in the task logs.
This creates and configures a new `dataflow` logger that should be
used by all operators for logs to be stored and shipped to S3 with
the airflow task logs.

Add a dataflow logger for operator logs

---

CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/dataset_pipelines.py
dataflow/dags/spi_pipeline.py
dataflow/operators/db_tables.py
dataflow/transforms.py
dataflow/utils.py
tests/operators/test_db_tables.py
tests/test_dags.py
tests/test_transforms.py
tests/test_utils.py

Builds on the fabulous work of @niross in #116, mostly just refactoring away our `field_mapping` class attribute in favour of a `table_config` one, which has a more well-defined process for handling nested relations/resources. This removes a custom SPI operator that knows about the data it's handling in favour of more data-agnostic operators.
As part of this, I've converted the SPI pipeline to use TableConfig. I've also migrated  `AdvisersDatasetPipeline` as well, as a small proof-of-concept for how to migrate a pipeline as well as to help test that the migration doesn't have any issues.
If this migration goes well, I'll look to migrate the rest of the pipelines in one or two more batches so that we can drop the old code/way relatively quickly. But in the mean time a "not-big-bang" …

Data Hub SPI Pipeline

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

This change adds indexes to several columns on the world_bank_tariffs table and removes the prf_rate column. 
I tested this locally and the indexes are created without issue the only concern I had is when the tables get swapped and renamed. The indexes will keep their original names (like sequences currently do) but I don't think this will be an issue as the temp tables are named with a timestamp so next run will be able to create indexes without issue.

Added indexes to WorldBankTariffPipeline

---

dataflow/dags/hmrc_pipelines.py
dataflow/operators/hmrc.py

Data files are uploaded on 11th of each month for the period 2
months before, so we set the job to run once a month on 12th.

Set a monthly schedule for HMRC uktradeinfo data

---

docker-compose.yml

At the moment, data-workspace and data-flow services (postgres/redis)
both run on the same port for the dev docker-compose file, meaning that
you can't run both at the same time locally.
This moves the local ports for data-flow's postgres and redis containers
up by 10000 so that both can be run at the same time.

Move local docker-compose ports

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/dataset_pipelines.py
dataflow/dags/spi_pipeline.py
dataflow/operators/activity_stream.py
dataflow/operators/common.py
dataflow/operators/company_matching.py
tests/operators/test_activity_stream.py
tests/operators/test_dataset.py

Both Data Hub and Market Access are Hawk-authenticated APIs that can be
iterated over in similar ways, so this strips out the datahub-specific
config and allows passing in any hawk credentials and the response keys
to look for when iterating through pages.

General `fetch from hawk api` operator

---

dataflow/dags/company_matching.py
dataflow/operators/company_matching.py

Use an instance property rather than a shared class attribute for the
table config on the company matching base pipeline, as the table config
is mutated during the DAG run - so we don't want to change a shared
table config instance.

Fix company matching pipeline

---

dataflow/dags/ons_pipelines.py

Geography dimension was renamed from trade-partner-geography to
ons-partner-geography, breaking the ONS pipelines.

Fix ONS pipelines after renamed dimension

---

dataflow/logging_config.py

We recently reduced airflow's logging to stdout to remove spam, mostly
in development environments. It still feels useful to have actual task
output logged to stdout though (e.g. "fetched page x", "processed x
records").

Log dataflow task output to stdout

---

bin/airflow-scheduler.sh

With global task parallelism set to 32 this gives us 16 task slots
and 16 sensor ones.
We don't want to set tasks any higher for the moment since some of
them are memory intensive and can cause an OOM.

Reduce default pool slots to 16 by default

---

dataflow/operators/db_tables.py
tests/operators/test_db_tables.py

DB table operations are usually quick, unless they get locked by
a long running transactions, in which case they can get stuck for
hours without alerting anyone.
Airflow `execution_timeout` that we set on these tasks doesn't seem
to work for this specific case. It will interrupt a sleep or a long
running operation, but doesn't seem to be able to interrupt a locked
DB transaction, so we set an additional statement timeout on these.

Add 10 minute statement timeout to DB table operators

---

CHANGELOG.md
dataflow/operators/db_tables.py
dataflow/utils.py

Adds a specific error for the `insert_data_into_db` task when there's no data in S3.

Add clearer error for insert step when no data

---

CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_pipelines.py

The pipeline was added alongside other ONS trade in goods pipelines but isn't actually required/used by anyone.
This also makes 'dependencies' available as a template variable so that they can be used to retrieve table names in DB queries.
Parent geography allows separating EU and non-EU countries to label them in the output CSV.

ONS UK seasonally adjusted trade in goods CSV pipeline

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py

Turns off catch up for daily csv dags as there is no need for historic runs

Turn off catchup for daily csv dags

---

CHANGELOG.md
dataflow/dags/ons_pipelines.py

Changes:
* Don't join on period for the label, as the period has two labels for
reason and this was leading to duplicated data.
* Include the period types (quarter or year)
These pipelines will probably fail when this is deployed, as the new
pipeline will pull in less data. We'll need to manually delete the
existing tables so that the comparison doesn't happen. This should be OK
as the data is not currently published for users.

Update UK trade in services pipelines

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

- Set schedule to yearly for DIT BACI pipeline
- Set schedule to yearly for world bank tariff pipelines
- Updated duty type field type to text on raw world bank tariff pipeline
- Added columns eu_rep_rate and eu_part_rate to world bank tariff pipeline
- Updated partner and reporter field types to text on world bank tariff pipeline

Updates to world bank tariff pipelines

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/maintenance.py
dataflow/utils.py
sample.env
tests/test_dags.py
tests/test_maintenance.py
tests/test_utils.py

Retries temporary boto EndpointConnectionError similar to how we retry API requests to other services
Deletes old S3 fetch cache older than the specified retention period (7 days by default).
Deletes old DB dataset tables (older than 3 days by default), only if a table with a matching prefix exists.

Add maintenance DAG with tasks to clean up old S3 files and DB tables

---

CHANGELOG.md
dataflow/dags/market_access_pipelines.py

The Market Access API has removed the `resolved_date` field, so we need
to update our pipeline to not expect it any more.
https://github.com/uktrade/market-access-api/pull/110

Update market access trade barriers pipeline

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

We scrape around 2.9M records of the interactions dataset daily, which
takes about 3 hours. We do this in chunks of 100, which feels pretty
inefficient. A PR on the data-hub-api
(https://github.com/uktrade/data-hub-api/pull/2749) allows clients to
specify their own page size, which will mean we can scrape in larger
chunks. This should reduce the total time-to-scrape as well as the time
to insert data into the DB (currently about 3.5 hours). Given a lot of
pipelines rely on this one, the faster it completes, the faster the
other pipelines can start and finish.
**Note:** This query param may not be available yet, so this won't start working immediately. But it's been merged so should get released sooner or later. 
I wonder if it's also worth thinking about doing delta updates, assuming that …

Increase page size for interactions dataset scrape

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_refresh_pipeline.py
dataflow/operators/csv_outputs.py

Fix the issue where the csv refresh dag was recreating files using the start date rather than the end date of the dag run.

Ensure end date of dag run is used in file name when refreshing csvs

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_yearly.py

Client has changed their mind...
- Reverts previous addition of rejected filter to current year wins report
- Adds rejected filter to yearly wins report

Remove rejected win filter from current year and add to yearly 

---

CHANGELOG.md
dataflow/operators/common.py

Relatively frequently we're waking up to find that some of our pipelines
seem to have just stalled in making requests, sometimes for 8+ hours. It
would be nice if these simply die rather than hang, so that we can
notice the problem sooner.

Set max time to retry requests to Hawk APIs

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py
dataflow/operators/common.py

We keep waking up to the interactions dataset having hung for hours
trying to fetch data. By adding timeouts on the requests we're hoping to
enable them to get retried if they do get stuck for a little while.
This also adds retries to the fetch task for the interactions pipeline
as a whole, so that if the entire task dies it will automatically retry.

Timeout requests after 5 minutes

---

CHANGELOG.md
dataflow/utils.py

Do not pass `self` when letting parent class handle `TypeError` for `DateTimeJsonEncoder`

Do not pass self in super call to JSONEncoder

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py

Add an `included_in_eu28` column to CSV export, using hard-coded list taken from http://gss-data.org.uk/concept?uri=http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fconcept%2Fons-partner-geography%2FB5.

Add included_in_eu28 via hard-coded list

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_yearly.py

Set start date of export wins yearly pipeline to 01/01/2016. To be picked up by the daily csv refresh dag.

Start export wins yearly pipeline from 2016

---

dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_pipelines.py

Adds rolling trade total, trade balance and rolling totals for each
of the metric types as separate rows of the output CSV file.
This removes parent geography column and is_eu28 CSV column since the
data is not currently being exported by the ONS SPARQL API.

ONS dataset 1 flat CSV structure

---

CHANGELOG.md
dataflow/operators/db_tables.py
dataflow/utils.py
tests/operators/test_db_tables.py

Allow for specifying a db schema at the dag level - as part of the ongoing dataset renaming work

Allow for specifying target schema in TableConfig

---

CHANGELOG.md
dataflow/dags/covid19_pipelines.py
dataflow/operators/common.py
tests/operators/test_dataset.py
tests/test_dags.py

- Adds a new csv import operator
- Adds a new dag for oxford covid-19 data

Add new oxford covid19 csv based pipeline

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py

Owen has come back with some changes we need to make to rationalise
these datasets.
* Rolling totals are now recorded as period types rather than measures.
* `measure` column is renamed `trade_value`.
* `trade_type`='goods' added to ONS dataset 1.
* `trade_type`='services' added to ONS dataset 3.
* `product_type` renamed to `trade_type` in ONS dataset 4.
* `geography_code` renamed to `ons_iso_alpha_2_code`.
* `geography_name` renamed to `ons_region_name`.
* 'derived' added to `marker` column for all derived values (e.g. trade
balance).
* Change e.g. '12 month rolling total' to e.g. '12 months ending'
* Use 'gbp' and 'gbp-million' value consistently.
* `type` renamed to `direction`.
* Added `marker` column to ONS dataset 1.
* Update dataset 3+4 queries to match dataset 1 style.

Updates ONS datasets 1, 3, 4

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py

* Change 'period_type' to '12 months ending' for rolling totals.
* Include a trade_type 'goods' for all rows.
* Rename 'total' to 'trade_value'
* Include 'derived' marker for all derived fields.
* Rename 'measure' to 'direction'
* Rename 'geography_code' to 'ons_iso_alpha_2_code'
* Rename 'geography_name' to 'ons_region_name'

Update ONS dataset 2 from feedback

---

dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py

This replaces the time offset based scheduling of CSV pipelines with
task dependencies on all related dataset pipelines. The pipelines
will all start at the same time as the dataset ones, but will wait
form them to continue using sensor tasks.
This will make sure that any failed pipeline will also fail any
upstream CSV pipelines, so that they are clearly marked and can
be rerun together.
This adds a relatively large number of sensor tasks to the Airflow
pool, so we'll need to check that this doesn't slow down / block
tasks in production and potentially tweak the pool sizes based on
that.

Add dependencies to daily and monthly CSV pipelines

---

CHANGELOG.md
Makefile
dataflow/dags/covid19_pipelines.py
dataflow/operators/csv_inputs.py
docker-compose.yml
tests/operators/test_csv_inputs.py
tests/test_dags.py

The 3 CSVs published by CSSE are combined into one table using a new operator that iterates over a mapping of source_urls and adds the URL key as a "type" column to the CSV data, allowing us to combine datasets that are published as separate files (for example separate import and export data CSVs) into one table, which is easier to use in the upcoming tools (since they don't generally allow UNION queries).
The data is transformed from a wide format (with a column for each date) into a normalized `(location, date, value)` list of measurements.
The new operator is using pandas to transform data, which means the entire dataset is loaded into memory. This is not an issue for the CSSE data, since it's relatively small (~60k rows), but might not be appropriate for larger datasets without some …

CSSE COVID-19 global time series

---

dataflow/dags/covid19_pipelines.py
tests/test_dags.py

Analysts need to access transformed and grouped CSSE data from tools
and data visualisations, so we need to save it in a DB table instead
of a CSV

Save transformed CSSE COVID data as a DB table

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/people_finder_pipelines.py
dataflow/operators/common.py
requirements.in
requirements.txt
sample.env
tests/operators/test_dataset.py
tests/test_dags.py

This adds an initial import pipeline and a CSV pipeline for People
Finder, the staff directory of DIT's Digital Workspace.
- Add ability to fetch data from client-generated JWT authenticated API
- Add import pipeline for People Finder
- Add daily CSV pipeline for People Finder data

Add People Finder integration

---

CHANGELOG.md
dataflow/dags/maintenance.py
tests/test_maintenance.py

Our S3 maintenance job cleans up old files used to store data during the
'fetch from api' phase of a pipeline. By default it drops data older
than 7 days. Some of our pipelines run monthly. Airflow pipelines record
their execution date related to the start of the period they're meant to
run for, which means that for monthly jobs the datetime tag on a
pipeline is always a month old - which means when our maintenance job
scans S3 files, it sees a date from a month ago and elects to clean it
up.
This patch forces our S3 maintenance job to always retain the latest
copy of the DAG run, regardless of how old it is.

Always keep S3 data for latest DAG run

---

CHANGELOG.md
dataflow/dags/tariff_pipelines.py

Adds a new field `cet_applies_until_trade_remedy_transition_reviews_concluded` to the global tariffs dataset

Add field to tariff pipeline

---

CHANGELOG.md
dataflow/dags/tariff_pipelines.py

Updates the global tariff data DAG. A new release of the tariff tool has been deployed which removes the `dumping_margin_applies` column.

Remove `dumping_margin_applies` column from tariff dataset

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
tests/test_dags.py

CSVs of People Finder data will be handled as data cuts in Data Workspace instead, so this pipeline is not needed

Remove People Finder CSV pipeline

---

CHANGELOG.md
dataflow/dags/consent_pipelines.py

We are hitting the internal domain for the consent service via http as requested but it returns https next/prev urls in it's response. This forces http for all requests.

Force http for consent service

---

CHANGELOG.md
dataflow/dags/people_finder_pipelines.py

The API on People Finder has been updated to expose a number of
additional fields (some have also been renamed for clarity). This adds
support for the new data structure to the People Finder pipeline.

Add additional fields to People Finder pipeline

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py
tests/test_dags.py

Adds a new dataset for data hub company referrals. The need for this comes from the firebreak project [Mapping referrals as they travel around the world](https://trello.com/c/QLJ6186n/70-mapping-referrals-as-they-travel-around-the-world)

Add new dataset for datahub company referrals

---

CHANGELOG.md
dataflow/dags/companies_house_pipelines.py
dataflow/operators/companies_house.py
tests/operators/test_companies_house.py
tests/test_dags.py

Adds a new pipeline for ingesting companies house company data. The data is hosted as 6 dated zipped csv files and is updated within 5 business days of the first of the month. This pipeline will run on the 10th of the month and will download and extract each file, writing the data to s3 in chunks of 10,000 rows

Add new companies house companies dataset

---

CHANGELOG.md
dataflow/dags/sharepoint_pipelines.py
tests/test_dags.py

Removes the public information asset register pipeline as it's deemed unnecessary (as requested by AL and JM).

Remove public information asset register dag

---

CHANGELOG.md
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_parsing_pipelines.py
dataflow/dags/ons_pipelines.py
dataflow/transforms.py

Adds some missing normalisation to the ons datasets. Requested by Owen and should be the last change before we go live.
- Normalise totals fields to int as "all values are rounded to millions"
- Replace empty strings with nulls on marker fields
- Replace 'N/A' and 'not-applicable' with 'not-available' on marker fields

Clean up normalisation on ons total and marker fields

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py

Update service delivery queries to include lead adviser details.

Add lead adviser details to service delivery csv pipelines

---

CHANGELOG.md
dataflow/dags/consent_pipelines.py

This PR is to disable `force_http` for Consent api, so that api calls default to https. We are moving from internal address to external. This should resolve the broken pipeline issue with Consent api, where subsequent page calls are moving from `http` to `https`.

disable `force_http` for consent api

---

dataflow/operators/dss_generic.py
tests/operators/test_dss_generic.py

Data Store Service has been accepting invalid DB identifiers for schemas
and table names (e.g. with spaces in) and sending these to Data Flow.
Data Flow then queries the Data Store Service again to read the table
config. When forming the URL, it puts the schema and table name in
without url encoding it, so when a space is present in the schema name
this isn't changed to %20 by Data Flow. DSS is protected by hawk
authentication, which is a signature formed from the URL and possibly
some other metadata. Data Flow therefore creates the hawk signature from
the non-encoded URL, but our request handler is smart enough to encode
the spaces to %20 before sending it off. When Data Store Service
receives this request and validates the signature, then, the URL doesn't
match the signature Data Flow …

URL quote schema/table names

---

CHANGELOG.md
dataflow/dags/consent_pipelines.py

This PR is to alter Consent dataset table/schema name to align with our new standards:
It's currently:
`public`.`consent_dataset`
changing it to:
`dit`.`consent_service__current_consents`

alter consent dataset's name to match our new standards

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py
dataflow/dags/dataset_pipelines.py

This PR is to update pipelines and remove Data Hub's obsolete field `accepts_dit_email_marketing` and use Consent service's data instead.

Remove contacts email marketing field

---

CHANGELOG.md
dataflow/dags/covid19_pipelines.py
dataflow/operators/covid19.py
tests/unit/operators/test_covid19.py
tests/unit/test_dags.py

Adds a new dataset for apple covid mobility data.
Trello Card: https://trello.com/c/Hy1eaWjT/609-apple-covid-19-mobility-trends-pipeline

Add apple covid19 mobility pipeline

---

CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/dataset_pipelines.py
dataflow/operators/contact_consent.py
dataflow/operators/db_tables.py
dataflow/utils.py
tests/unit/operators/test_db_tables.py

This PR adds an optional overridable task to transform/manipulate data between `check-temp-table-data` task and `swap-dataset-table` task.
This is utilised within contacts pipeline to join email consent data from consent dataset obtained from Consent service and prefill that to contacts dataset. This should improve performance of queries otherwise had to resort to joining contacts dataset and consent dataset.

adding a new transform data task to pipelines

---

dataflow/dags/dataset_pipelines.py

Changing default value of `email_marketing_consent` field of `contacts_dataset` to `False`, so that records that don't match with data in `consent_dataset` will remain `False`.

Changing default value of email_marketing_consent field

---

dataflow/dags/base.py

The swap_dataset_tables has failed a few times recently after timing out. The reason for this is unclear but restarting the task manually seems to fix it. This PR ensures the task is retried automatically.

Retry the swap_dataset_tables task twice as this often fails

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_monthly.py
dataflow/dags/dataset_pipelines.py

This PR removes Data Hub's obsolete field `accepts_dit_email_marketing`. Uses new field `email_marketing_consent` instead.

Removing old email marketing consent field

---

CHANGELOG.md
dataflow/dags/market_access_pipelines.py

The market access team have released a new version of their barriers
endpoint which we should switch over to so that they can decommission
the old endpoint.

Update market access trade barriers endpoint

---

CHANGELOG.md
dataflow/dags/dun_and_bradstreet_pipelines.py

- Rename uk dnb tables to differentiate them from the global company data
- Move uk dnb tables to the new dun_and_bradstreet schema to match global tables

Rename dnb tables and move to new dun_and_bradstreet schema

---

manifest.yml

Both manual `cf push` and the Jenkins deployment pipeline preserve bound services. Typically also for other projects in the department, the services are not specified in the manifest.

No explicitly bound services to support multiple environments in the same space

---

dataflow/dags/market_access_pipelines.py

Waiting for market access team to update the `unarchived_by` field to be a dict.
Pull in the archived/unarchived data fields for market access trade
barriers and create a related table to track when trade barriers' status
field was changed.

feat: additional fields for trade barriers

---

dataflow/dags/market_access_pipelines.py

We tried to pull these in but they're null everywhere, which the
pipeline then rejects. So let's not grab these for now.

fix: ignore unarchived_* fields for now

---

.cfignore
CHANGELOG.md
Procfile
README.md
alembic.ini
alembic/README
alembic/env.py
alembic/script.py.mako
alembic/versions/bf30b3dbebb4_create_metadata_table.py
dataflow/dags/base.py
dataflow/dags/ons_parsing_pipelines.py
dataflow/models.py
dataflow/ons_scripts/uktradeinservicesservicetypebypartnercountrynonseasonallyadjusted/UK trade in services by partner country.py
dataflow/ons_scripts/uktradeinservicesservicetypebypartnercountrynonseasonallyadjusted/info.json
dataflow/operators/db_tables.py
docker-compose.yml
requirements.in
requirements.txt
tests/unit/conftest.py
tests/unit/dags/test_base.py
tests/unit/dags/test_ons_parsing_pipelines.py
tests/unit/operators/test_db_tables.py
tests/unit/utils.py

This adds alembic to data-flow so that it can set up and manage a
metadata table for data-flow pipelines/tables. In the beginning we will
only track the table schema, table name, source last modified date, and
pipeline table swap date. Where a pipeline does not explicitly define a
method to determine the source data modified date, we leave the
corresponding column in the metadata column empty for now. In the future
we are likely to want to fill this in. I'm choosing not to do this now
as it isn't clear on the correct timestamp to store here for real-time
systems, which most of the remaining pipelines will represent.
Note: this patch runs DB migrations as part of app startup, which isn't
best practice, though is what we generally do on our other apps at the
moment. I've made a ticket in …

Add metadata table with source date tracking for ONS datasets

---

manifest.yml

Without this change, pushing gets the following in the log (lots has been snipped out)
```
**WARNING** buildpack version changed from 1.7.15 to 1.7.19
Running command git clone -q https://github.com/GSS-Cogs/gss-utils.git /tmp/pip-req-build-o_tjldhk
ERROR: Command errored out with exit status 1:
error: invalid command 'bdist_wheel'
```
So I suspect something's up with the latest PaaS Python buildback

build(deps): pin buildpack to one with working git

---

Jenkinsfile

Jenkins deployments have been broken for a few days because the `userRemoteConfigs` argument seems to now be required by gitscm checkout.

fix(ci): add repo url to git checkout in ci

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py

The Data Hub team have added a new field to Investment Projects for `country_investment_originates_from`
https://github.com/uktrade/data-hub-api/blob/master/CHANGELOG.md#data-hub-api-3530-2020-08-17
It has been added to Data Hub investments dataset API endpoint.
This PR adds this field to `investment_projects_dataset` table.

Add country_investment_originates_from field to investment dataset

---

CHANGELOG.md
dataflow/dags/people_finder_pipelines.py

The (mostly empty) `contact_email` field was overwriting the main
`email` field by accident due to a typo in the field mapping

Fix incorrect column name in People Finder pipeline

---

CHANGELOG.md
dataflow/dags/maintenance.py
tests/unit/test_maintenance.py

- Include schemas other than public in db cleanup task
- Excludes _user* and postgres internal schemas

fix: include non-public schemas in table maintenance dag

---

CHANGELOG.md
dataflow/dags/covid19_pipelines.py
dataflow/dags/dashboard_pipelines.py

- Use the new combined "countries territories and regions" reference dataset in dashboard pipeline queries
Closes: https://trello.com/c/kCcMDbtO/828-countries-and-territories-with-overseas-regions-reference-data

feat: use new country/territory dataset in dashboard queries

---

requirements-tensorflow.txt
requirements.in

Even though it doesn't use the notifications client, it attempts to import the code of the DAGs, and fails because it can't import it

fix: ensure tensorflow worker has notifications client

---

dataflow/dags/base.py
dataflow/dags/ons_pipelines.py
dataflow/ons_scripts/uk_trade_in_goods_all_countries_seasonally_adjusted/main.py
dataflow/ons_scripts/uktradecountrybycommodity/main.py
dataflow/operators/db_tables.py
tests/unit/operators/test_db_tables.py
tests/unit/utils.py

The gss-utils scraper, by default, implements file-based caching for
requests. When we run our polling pipeline task in air-flow, we
initialise a new scraper each time we want to check the last modified
date but it resolves to the same file cache, meaning that we don't
actually retrieve the last data every time we poll. Providing a custom
session overrides the default caching logic meaning that every poll will
check for the latest date.
We originally had the polling loop as part of the main
scrape/transform/load task in order to minimise the latency between
airflow running tasks. This feels not ideal upon further consideration:
We set the polling jobs to run fairly regularly, possibly even every
day, despite (currently) only expecting new data to be ingested once
a month or quarter. …

Polling pipeline tweaks

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py
tests/unit/test_dags.py

Finding the latest interaction date for a contact/advisor is a quite costly query and has caused some database outages recently. To remedy this we add two new pipelines to run overnight which will speed up custom queries on the site.

feature: contact and advisor last interaction pipeline

---

CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/ons_pipelines.py
dataflow/ons_scripts/uktradecountrybycommodity/main.py
dataflow/operators/db_tables.py
dataflow/utils.py
tests/unit/operators/test_db_tables.py

Rather than using pandas.DataFrame.to_sql to load data from the
dataframe to the DB, we instead rely on Postgres's native copy_from
functionality to provide a significant increase in data load times. In
order to do this we need to define the table ourselves, and this
actually brings us more in line with the standard pipeline where we now
declare our table columns in a (Single)TableConfig object up front, and
manipulate the resulting data into the table using source/target field
names.
This large ONS dataset was using multiprocessing to load/clean/transform
two ONS dataset sheets at the same time - unfortunately in testing this
has ended up with a peak memory usage that is occasionally too high,
resulting in one of the subprocesses being killed. Python doesn't detect
this very cleanly and …

feat: use raw copy to load data

---

.pylintrc
CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/companies_house_pipelines.py
dataflow/dags/consent_pipelines.py
dataflow/dags/covid19_pipelines.py
dataflow/dags/dashboard_pipelines.py
dataflow/dags/data_workspace_pipelines.py
dataflow/dags/dataset_pipelines.py
dataflow/dags/dun_and_bradstreet_pipelines.py
dataflow/dags/export_wins_dashboard.py
dataflow/dags/hmrc_pipelines.py
dataflow/dags/market_access_pipelines.py
dataflow/dags/people_finder_pipelines.py
dataflow/dags/sharepoint_pipelines.py
dataflow/dags/spi_pipeline.py
dataflow/dags/tariff_pipelines.py
dataflow/operators/db_tables.py
tests/unit/operators/test_db_tables.py

- Specify at the dataset level whether to use xcom date or utcnow when setting the last modified date for a table.
- Cleanup db_tables.py to fix pylint issues
Closes: https://trello.com/c/FyJUmHp1/887-add-last-updated-metadata-to-dataset-pipelines

feat: allow for setting `source_data_modified_utc` to utcnow()

---

CHANGELOG.md
dataflow/dags/csv_pipelines/csv_pipelines_daily.py
dataflow/dags/csv_pipelines/csv_pipelines_yearly.py
dataflow/dags/derived_report_table_pipelines.py
tests/unit/test_dags.py

There are currently 156 queries on data workspace that produce the same report based on a few variables (region, sector, financial year). If a change needs to be made to the query someone has to go through and update every one of those manually.
This PR
- Adds a new derived table that handles much of the logic of our existing queries and provides a simpler way for data managers to write these reports.
- Updates the export wins csv pipelines to use the new table

feat: new derived export wins table to aid reporting

---

CHANGELOG.md
dataflow/dags/covid19_pipelines.py
dataflow/dags/derived_report_table_pipelines.py

A few small fixes to some pipeline issues encountered over the last few days.
- Run the google covid pipeline daily 
- Allow null columns on the derived export wins pipeline
- Use the high memory queue for the google covid dataset fetch operation
- Add region name and region code fields to oxford covid dataset

fix: covid and export wins pipeline cleanup

---

CHANGELOG.md
dataflow/dags/company_matching.py
dataflow/operators/dss_generic.py
tests/unit/operators/test_dss_generic.py
tests/unit/test_dags.py

The dataset will be processed by the DSSGenericPipeline. At the end of the processing the matching pipeline is triggered to get match_ids for the data.

feature: HMRC Exporters Matching Pipeline

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py
tests/unit/test_dags.py

Adds a new activity stream pipeline for the new return to office service
Closes: https://trello.com/c/gLLzk1Tm/888-data-pipeline-for-the-dit-desk-booking-tool

feat: return to office pipeline

---

CHANGELOG.md
dataflow/dags/company_matching.py
dataflow/operators/company_matching.py

Some of the datasets in data-flow pipelines should use the update endpoint in the matching service rather then the match endpoint to keep the matching backend up to date with the latest company information.

feature: update matching service company data

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py
tests/unit/test_dags.py

This PR adds a new pipeline to get data from Activity Stream's Maxemail email sent campaigns.

adding a new pipeline for maxemail email campaign sent from activity stream

---

dataflow/dags/activity_stream_pipelines.py

campaign id is not properly formatted in Activity Stream feed. Removing it for now, will be added back once it is fixed.

removing campaign id for now until Activity Stream side is fixed

---

CHANGELOG.md
alembic/versions/e7b0c0fba2e3_table_deps_save_and_restore.py
dataflow/models.py
dataflow/operators/db_tables.py
tests/unit/operators/test_db_tables.py

Support the swapping of tables with dependencies such as views or materialized views.
Before a table is swapped any dependencies are stored in the database and restored after
a successful swap.

feature: preserve dependencies on swap table

---

CHANGELOG.md
dataflow/dags/ons_pipelines.py
tests/unit/dags/test_ons_pipelines.py

Link up more ONS pipelines with their env vars so that emails are sent
out when the pipelin runs finish.

feat: configure email alerts for more ONS datasets

---

CHANGELOG.md
dataflow/dags/dashboard_pipelines.py

The original query for `DataHubMonthlyInvesmentProjectsPipline` was attempting to join with the sectors reference dataset on a transformed field which was returning incorrect results. This fix updates the query to join on the actual sector name but return the transformed sector as before.

fix: join on non-transformed sector field

---

CHANGELOG.md
dataflow/dags/covid19_pipelines.py

Ensure there are no countries with empty iso 2 or 3 codes

fix: update field mapping for john hopkins covid query

---

CHANGELOG.md
dataflow/dags/derived_report_table_pipelines.py

Fixes issue where fetch task was running out of memory

fix: move export wins derived to high mem queue

---

CHANGELOG.md
dataflow/dags/base.py
dataflow/dags/csv_pipelines/csv_refresh_pipeline.py
dataflow/dags/tensorflow_pipelines.py

A lot of our pipeline failures are due to transient issues, e.g.
instances being killed+restarted, APIs having hiccups, etc. By setting
default retries to 3 for all tasks across (almost) all pipelines, we
should reduce the need for manually intervening to fix jobs that have
only more significant issues.

feat: set default retries globally

---

docker-compose.yml

Use same Postgres version (v10) in local docker deployment as in the production environment.

Change Postgres version in local docker deployment to match production

---

CHANGELOG.md
dataflow/dags/sharepoint_pipelines.py
dataflow/operators/sharepoint.py
tests/unit/operators/test_sharepoint.py

There is no way to paginate graph api responses when mxing data types (fields vs columns). To fix this a sharepoint request has been broken down into two parts.
1. Fetch the column names for the list
2. Paginate through the list item data
Closes: https://trello.com/c/UOWABZY5/797-information-asset-register-shows-only-first-200-rows

fix: pagination for sharepoint lists

---

CHANGELOG.md
dataflow/dags/dataset_pipelines.py
dataflow/operators/ons.py

The ons postcode dataset now keeps track of data for different publication dates. Materialized views allow access to the data for a specefic publication date.

fix: ONSPostcodePipeline

---

CHANGELOG.md
dataflow/operators/common.py

We seem to get a separate Sentry event for every Hawk failure, even if they're all raised in the same place. This avoids any Sentry event on all but the last failure.
Also increasing number of attempts and delay between them since if a pipeline fails, suspect the first thing that will be done in most cases would be to retry, so we might as well have more retrying up front.

Less logging to Sentry, more retries and higher delay between them for Activity Stream sources

---

docker-compose.yml
sample.env

Used a single network for all Data Infrastructure apps/services so that
they can be linked together more easily when working locally, e.g. to
connect data-flow and data-store-service.

feat: use shared data infrastructure dev network

---

dataflow/operators/api.py

Increasing number of attempts and delay between them since if a pipeline fails, suspect the first thing that will be done in most cases would be to retry, so we might as well have more retrying up front.
We also seem to get a separate Sentry event for every Hawk failure, even if they're all raised in the same place. This avoids any Sentry event on all but the last failure.
This was initially attempted in 3ec893d76be97319157bae0ca3e5ac248c9cad46 and 890ff970845c97bf6de356a6dda3d790bbf6af58, but that changed the wrong `_hawk_api_request` function.
Leaving potentially merging the two functions until later.

feat: longer waitsm more retries, and lower log level for Activity Stream (actually this time)

---

CHANGELOG.md
dataflow/dags/activity_stream_pipelines.py

Rename lite to match naming conventions before we turn them on on prod

fix: update lite pipelines to match data standards

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/companies_house_pipelines.py
dataflow/operators/companies_house.py
sample.env
tests/unit/operators/test_companies_house.py
tests/unit/test_dags.py

Adds companies house "persons with significant control" pipeline. 
The data is currently comprised of ~8 million records spread across 17 files. This PR adds a new environment variable `COMPANIES_HOUSE_PSC_TOTAL_FILES` which will need to be updated if/when a new file is added.

feat: companies house persons of control pipeline

---

CHANGELOG.md
dataflow/config.py
dataflow/dags/zendesk_pipelines.py
dataflow/operators/zendesk.py
dataflow/utils.py
tests/unit/operators/test_zendesk.py
tests/unit/test_dags.py
tests/unit/test_utils.py

Two new zendesk pipelines were added for storing zendesk tickets for `DIT` and `UKTRADE` zendesk account.
- new schema `zendesk` in `datasets` database
- new tables in database `datasets` on `zendesk` schema 
- `dit_tickets`
- `uktrade_tickets`
- adding new directory in bucket named `upstream` for persistent storage of files
- files in `import-data` can be deleted after few days
- at least once a day each pipeline is executed
- task fetches daily tickets data from zendesk API
- daily data is stored in `upstream` directory ie `upstream/zendesk_<table_name>/20201122.json`
- all files in directory `upstream/zendesk_<table_name>/` are copied to `import-data/<table_name>/<ts_nohash>/`
- these files are processed into a `datasets` table as in any other pipeline
This variables have to be added …

feature: zendesk pipelines

---

dataflow/config.py
dataflow/dags/zendesk_pipelines.py
dataflow/operators/zendesk.py
sample.env
tests/unit/operators/test_zendesk.py

This PR adds a function in the `fetch-daily-tickets` which removes tickets related to covid19 from the `DITZendeskPipeline`, as these tickets are not necessary to bring in to Data Workspace. 
It also adds logic to transform fields from the data export to match the structure of the fields from the API in the `DITZendeskTicketsPipeline`.

Update fields and exclude covid tickets in zendesk DIT pipeline

---

dataflow/dags/ons_pipelines.py

We normally run these two ONS datasets only a few times a quarter, in
line with their anticipated release schedule. We've received
notification this time that the datasets are being released fairly late,
so need to run the pipeline more regularly to make sure we catch the
release date. After this release, we should be able to switch it back to
the old cron schedule to ensure we don't have this running every day for
3 months for no reason.

fix: update ONS schedules for delayed data release

---

dataflow/dags/zendesk_pipelines.py
dataflow/operators/common.py
tests/unit/test_dags.py

This PR adds two pipelines which bring in groups data from zendesk on a weekly basis. These tables can then be joined with the zendesk tickets tables to get information about the groups within DIT who are handling tickets. 
As the zendesk API requires a `basic` auth token and a specific content type, this PR also adds two new optional arguments to `fetch_from_api_endpoint` operator which allow for specifying the auth type and any additional headers.

Add zendesk groups pipelines

---

dataflow/dags/csv_pipelines/csv_pipelines_monthly.py
dataflow/operators/contact_consent.py

Fixes 2 small issues caused by the data hub table migrations
- Missing schema name in contacts consent update
- Missing column name in daily omis query

fix: add missing column and schema names

---

dataflow/operators/db_tables.py
dataflow/utils.py
requirements-tensorflow.txt
requirements.in
requirements.txt
tests/unit/test_utils.py

In some cases, we load JSON manually into S3, and in some of those, the JSON is larger than 1GB. Before this commit, this data is loaded into memory at least twice, and most workers don't have enough memory for this.
We could bump the memory, but in general, I think we should be making small moves to reduce memory usage/support streaming, in order to support larger datasets that can't be loaded into memory on a single machine.
The use of the function insert_csv_data_into_db was removed in 2792f69f18c24e6741fea83f9bdbccab11ab28ee, and this was the only use of json=False/jsonify=False, so opting to remove the function and these attributes.
~* [ ] Has the README been updated (if needed)?~

feat: avoid storing all JSON in memory when loading from S3

---

dataflow/dags/ons_pipelines.py

Reverts uktrade/data-flow#403
We temporarily expanded the pipeline schedule for these ONS tasks due to delayed data releases. Now that these have both run, we can switch them back to a fortnight (ish) window every quarter.

Revert "fix: update ONS schedules for delayed data release"

---

dataflow/dags/activity_stream_pipelines.py

The URL and bounced reasons are on `object`, not on the top level

fix: correct MaxEmail event pipeline

---

dataflow/dags/zendesk_pipelines.py

This PR fixes a bug occurring in production when processing the `uktrade_zendesk_past_tickets` file. 
Previously I had thought that if there was a value for the `organization` key in a ticket, it would be a dict with an `id` key, however it turns out there are two tickets for which organization is an int. This PR adds logic to be able to handle both cases.

Account for 'organization' being an int or dict

---

dataflow/operators/companies_house.py

The result of archive.open is a ZipExtFile, and its readlines method reads all of its lines into a list.
However, ZipExtFile extends from BufferedIOBase https://github.com/python/cpython/blob/3.7/Lib/zipfile.py#L785 which extends from IOBase https://github.com/python/cpython/blob/3.7/Lib/io.py#L78 and from https://docs.python.org/3/library/io.html#io.IOBase
> IOBase (and its subclasses) supports the iterator protocol, meaning
> that an IOBase object can be iterated over yielding the lines in a
> stream.
so we can just avoid the readlines method, and use the ZipExtFile directly.
It would be great if we could avoid loading the raw zip file in memory, but AFAIK the directory for zip files is at the _end_ of the file, so I don't think it's possible to stream-download a zip while unzipping its …

feat: use less memory in Companies House pipelines

---

dataflow/config.py
dataflow/dags/enquiry_mgmt_pipelines.py
tests/unit/test_dags.py

Details
- new schema `enquiry_mgmt` in `datasets` database
- one new table `enquiries` in database `datasets` on `enquiry_mgmt` schema 
Process
- pipeline is executed at least once a day
- task fetches daily all enquiries from `http://enquiry-mgmt.trade.gov.uk`
- data is processed the usual way through files in buckets and inserted into table
Configuration
- ENQUIRY_MGMT_BASE_URL
- ENQUIRY_MGMT_HAWK_ID
- ENQUIRY_MGMT_HAWK_KEY

feature: enquiry mgmt enquiries pipelines

---

dataflow/dags/dun_and_bradstreet_pipelines.py

The query used in the https://data.trade.gov.uk/admin/datasets/datacutdataset/8a23bbbd-e31a-41d4-b459-ab1be387fbd8/change/ dataset is timing out due a large number of rows. This PR adds an index to the columns used in the join clause to speed up the query.

feature: add index to dnb global and uk tables to speed up query join

---

dataflow/operators/common.py
tests/unit/operators/test_dataset.py

The PeopleFinder API has changed and no longer works when "Token" is passed. As the PeopleFinder pipeline is the only one that uses JWT this change has been made to the common fetch_from_jwt_api method.

fix: use "Bearer" instead of "Token" for JWT request header

---

dataflow/dags/companies_house_pipelines.py

Set the primary key for companies house companies to the company number rather than an auto-incrementing int. This resolves 2 issues:
1. As the companies api returns companies in alphabetical order, every time a company is added and the pipeline rerun the id for our record would change.
2. We currently have duplicate records for nearly every table in the dataset, this is due to a failure and rerunning of the dag. Were this to happen again the dag would fail.

fix: use company number as primary key

---

dataflow/dags/dataset_pipelines.py
dataflow/dags/export_wins_dashboard.py

renaming export wins table names to match new standards
- export_wins_advisers_dataset
- export_wins_breakdowns_dataset
- export_wins_dashboard_data
- export_wins_hvc_dataset
- export_wins_wins_dataset

renaming export wins table names to match new standards

---

dataflow/dags/people_finder_pipelines.py
dataflow/operators/common.py
tests/unit/operators/test_dataset.py

The People Finder API is authenticated using JWT, which has an expiry
time that is validated by the server. At the moment we are setting the
expiry time as 60 seconds from the start of the pipeline, and re-using
the same payload/auth token for every subsequent request, meaning that
if the pipeline takes more than a minute we start to see failures.
We should generate a new token with a short(er) expiry for each request,
so that the pipeline can take an arbitrary amount of time to run and we
won't send expired tokens.

fix: build payload for each request

---

dataflow/dags/activity_stream_pipelines.py
dataflow/dags/base.py
dataflow/dags/cabinet_office_pipelines.py
dataflow/dags/companies_house_pipelines.py
dataflow/dags/company_matching.py
dataflow/dags/comtrade_pipelines.py
dataflow/dags/consent_pipelines.py
dataflow/dags/covid19_pipelines.py
dataflow/dags/dashboard_pipelines.py
dataflow/dags/data_workspace_pipelines.py
dataflow/dags/dataset_pipelines.py
dataflow/dags/derived_report_table_pipelines.py
dataflow/dags/dun_and_bradstreet_pipelines.py
dataflow/dags/enquiry_mgmt_pipelines.py
dataflow/dags/export_wins_dashboard.py
dataflow/dags/gateway_to_research_pipelines.py
dataflow/dags/hmrc_pipelines.py
dataflow/dags/market_access_pipelines.py
dataflow/dags/ons_pipelines.py
dataflow/dags/people_finder_pipelines.py
dataflow/dags/sharepoint_pipelines.py
dataflow/dags/spi_pipeline.py
dataflow/dags/tags_classifier_prediction_pipeline.py
dataflow/dags/tags_classifier_train_pipeline.py
dataflow/dags/tariff_pipelines.py
dataflow/dags/zendesk_pipelines.py
tests/unit/test_dags.py
tests/unit/utils.py

We might want to have some tests that enforce some "basics" across all of our DAGs. Here's an example test that checks that every "standard" DAG returns a DAG task from `get_fetch_operator` with >0 retries configured so that any transient/trivial errors are automatically recovered from. This will hopefully remove a subset of a class of errors from requiring manual intervention.

test: ensure all fetch tasks have retries

---

dataflow/dags/__init__.py
dataflow/dags/base.py
dataflow/dags/comtrade_pipelines.py
dataflow/dags/ons_pipelines.py
dataflow/ons_scripts/uk_total_trade_all_countries_non_seasonally_adjusted/main.py
dataflow/ons_scripts/uk_trade_country_by_commodity/main.py
dataflow/ons_scripts/uk_trade_in_goods_all_countries_seasonally_adjusted/main.py
dataflow/ons_scripts/uk_trade_in_services_service_type_by_partner_country_non_seasonally_adjusted/main.py
dataflow/operators/comtrade.py
dataflow/operators/db_tables.py
dataflow/utils.py
docker-compose.yml
requirements-tensorflow-worker.txt
requirements.in
requirements.txt
tests/unit/conftest.py
tests/unit/dags/test_base.py
tests/unit/operators/test_comtrade.py
tests/unit/operators/test_db_tables.py
tests/unit/test_dags.py
tests/unit/utils.py

The goods pipeline is trying to pull in >500 million rows, so a standard
pipeline will not work as that does row-by-row inserts. We need to do
bulk inserts via postgresql copy. This patch does the following:
1) Update the "_FastPollingPipeline" to a mouthful of a
"_PandasPipelineWithPollingSupport". This pipeline type loads
data into pandas DataFrames and writes the csv output of this
directly into postgres via a `copy` command. This renaming removes
some of the vagueness of the "fast" naming and hopefully makes it
easier to grok on sight.
2) Change the Comtrade Goods pipeline from a standard one to a Pandas
one, and re-writes the logic to use pandas Data Frames, chunking data
into blocks of 1 million to reduce maximum memory footprint. This
required adapting the Pandas pipeline's main …

Speed up comtrade goods

---

dataflow/dags/hmrc_pipelines.py
dataflow/operators/hmrc.py
tests/unit/operators/test_hmrc.py

* Pull data from as far back as their records go (generally 2009).
* Add a new column including the name of the file the row has come from
* Check for "latest" files within the last two months. Running them today, the latest data is from October but the pipelines only look at November.

Update HMRC pipelines

---

dataflow/dags/derived_report_table_pipelines.py
dataflow/dags/export_wins_dashboard.py

The pipeline that created the `export_wins_wins_dataset` table is now
creating our "name standard" `exports_wins__wins_dataset` table. Some of
the downstream pipelines weren't updated to use the new table name.

fix: migrate export wins dependent pipelines

---

dataflow/dags/export_wins_dashboard.py

These were highlighted after we scrapped the staging datasets DB,
meaning that old tables with these deprecated names were no longer
available.

fix: add dependencies for export wins matching

---

dataflow/dags/base.py
dataflow/dags/csv_pipelines/ons_csv_pipelines.py
dataflow/dags/ons_pipelines.py
tests/unit/dags/test_base.py
tests/unit/dags/test_ons_pipelines.py
tests/unit/utils.py

Our ONS pipelines come in two parts - polling pipelines that update
master dataset tables, and CSV generators that use the master datasets
to write out the latest data to CSV. The CSV pipelines use the
`dependencies` attribute to set up external task sensors on the polling
pipelines checking for a successful run of the `swap-dataset-tables`
task. This task only runs when the polling pipeline detects new data is
available, otherwise after a period of polling that task (and all
others) are skipped for the day. The `dependencies` framework ignores
skipped tasks.
The problem with this is that the external task sensor, on days where
new data isn't available, ends up timing out because it doesn't find a
successful run of the `swap-dataset-tables` task. This throws errors,
which get reported in …

fix: allow triggering DAGs from other DAGs

---

.env.test
Makefile
docker-compose-test.yml
tests/integration/test_api.py

Although it might have been me to push for the test that asserts that AIRFLOW__API__AUTH_BACKEND is respected, I think the test that gives a 401 if the credentials are wrong is enough
This is done as a precursor to integration tests for publishing the UK tariff

tests: refactor integration tests to avoid mocking + delete test
